# Generated by Django 6.0.2 on 2026-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fav_genre', models.CharField(max_length=30)),
                ('main_instrument', models.CharField(max_length=40)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
