# Generated by Django 6.0.2 on 2026-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_genre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_instrument',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
