# Generated by Django 6.0.2 on 2026-05-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
