# Generated by Django 6.0.2 on 2026-05-02 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('arranger', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='music_sheets/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
