# Generated by Django 6.0.2 on 2026-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsheet',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='musicsheet',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='intermediate', max_length=20),
        ),
    ]
